name: Export to HTML

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download requirements
        run: |
          npm install -g resume-cli
          npm install jsonresume-theme-classy

      - name: Export the html file
        run: |
          resume export index --format html --theme classy

      - name: Commit files
        run: |
          git config --local user.name "github-actions"
          git add index.html
          git commit -m "Updating index"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
